### ISSUE TITLE
Serialization performance vs. `ptr-poker`, `mason`

### ISSUE THREAD

**Issue by raehik** [oberblastmeister/seraph#1]
[ptr-poker](https://github.com/nikita-volkov/ptr-poker) is a serialization library inspired by [store](https://github.com/mgsloan/store). [mason](https://github.com/fumieval/mason) is currently the fastest "classic" growing buffer bytestring builder out there. I wonder how seraph's serialization performs against them both.

For reference, there is https://github.com/haskell-perf/strict-bytestring-builders and https://github.com/haskell-perf/serialization (pretty old). I've found these aren't the best for benchmarking all parts of an en/decoding lib though. (Maybe the latter repo is better, but it's super old.)

---

This is mostly an excuse to say I'm super interested in seraph and would love to help out. I've been writing some high performance en/decoding Haskell recently alongside [binrep](https://github.com/raehik/binrep) which is convenient for testing and benchmarking the sort of data low-level en/decoders should expect, and is especially happy to work with pre-allocating serializers.

**Comment by oberblastmeister** [comment]
I have some more "real world" benchmarks, but those other two libraries don't support deriving on data types so I just made some micro benchmarks. All the benchmarks basically did this:
```haskell
test is = run (foldMap put is)
{-# NOINLINE test #-}

```
These were the results:
```
benchmarking testing/pp
time                 2.579 ms   (2.546 ms .. 2.631 ms)
                     0.998 R²   (0.995 R² .. 1.000 R²)
mean                 2.578 ms   (2.556 ms .. 2.616 ms)
std dev              93.12 μs   (64.74 μs .. 128.4 μs)
variance introduced by outliers: 21% (moderately inflated)

benchmarking testing/seraph
time                 817.7 μs   (803.6 μs .. 834.3 μs)
                     0.998 R²   (0.996 R² .. 0.999 R²)
mean                 811.6 μs   (803.9 μs .. 820.2 μs)
std dev              28.27 μs   (23.94 μs .. 38.49 μs)
variance introduced by outliers: 25% (moderately inflated)

benchmarking testing/mason
time                 451.2 μs   (446.0 μs .. 455.0 μs)
                     0.997 R²   (0.995 R² .. 0.999 R²)
mean                 461.7 μs   (450.0 μs .. 483.0 μs)
std dev              55.87 μs   (33.36 μs .. 85.86 μs)
variance introduced by outliers: 83% (severely inflated)
```
I analyzed GHC core to discover the reasons for these performance differences. Both `ptr-poker` and `seraph` calculate the size beforehand. `ptr-poker` is the slowest, because it tracks sizes **lazily** in the `Monoid`. This is equivalent to doing something like `foldr (+) 0 xs`, which has many recursive calls. It also creates closures in every loop iteration, so it would probably benefit from `oneShot` optimizations. Both `seraph` and `mason` compile down to a loop writing to a pointer. I think the only reason why `mason` is faster is because it does a manual worker-wrapper transformation for the internal `Builder` monad. I did this before but was not convinced by the performance benefits. If I add it in again, `seraph` should be on par with `mason`.

**Comment by oberblastmeister** [comment]
`ptr-poker` and `mason` are `ByteString` builder libraries, while `seraph` is a serialization library that happens to contain a `ByteString` builder implementation. I'm not sure I completely understand what `binrep` does. Is it a serialization library with better control over the representation and has validation when deserialization? Are you looking for a builder to use for that library?

**Comment by raehik** [comment]
> I'm not sure I completely understand what binrep does. Is it [...]

Yes, something like that. binrep is binary data modelling. It's not an automatic serialization lib, I want to piggyback off existing libs and wrap them in strange type classes. That's led me to looking for faster parser & serializers. I'm happy with flatparse for parsing (though your metalparsec looks really cool) and became curious to see if a less safe constant buffer approach could substantially beat mason.

Thanks for your benchmarks & analysis. By worker-wrapper, do you mean how `Builder` and `unBuilder` are used? (I'm not used to catching that pattern in the wild.)

Also thanks to this, I finally notice that mason has a constant buffer mode! Though the serialization primitives it provides will be doing size checks anyway.

**Comment by oberblastmeister** [comment]
> By worker-wrapper, do you mean how Builder and unBuilder are used? (I'm not used to catching that pattern in the wild

I mean using unboxed types like `Addr#`

**Comment by raehik** [comment]
Right. I wrote an unboxed ptr-poker-like and found at least 10% extra performance -- but I don't really know what I'm doing, or how to understand core, and the benchmarks I was using were very flimsy.

I get that seraph is a serialization lib rather than a one-way bytestring serializer. I've got a better idea of serializing lib performance now thanks to your benchmarks. Closing, cheers.
